### ISSUE TITLE
add new task : learning descriptor for point cloud registration

### ISSUE THREAD

**Issue by humanpose1** [nicolas-chaulet/deeppointcloud-benchmarks#118]
It would be great to also have a benchmark for the descriptors. So that we could compare the different convolutions on this task (KPConv, RSConv, pointnet++....).
Dataset : [3DMatch](http://3dmatch.cs.princeton.edu/)
1) we have to download the dataset (it is RGBD frames)
2) create fragments
3) find pair of similar patches from different fragments
4) (optionally some preprocessing)
5) siamese network to learn descriptors on patches

An other option is to learn descriptor on the fragment itself (like [FCGF](https://chrischoy.github.io/publication/fcgf/) like a segmentation network) and not on patches.

**Comment by nicolas-chaulet** [comment]
That's a great idea! I think the starting point is to add 3d match as a torch geometric dataset and implement the relevant transformations to make it training ready (a bit like how shapenet gets processed from raw individuals files and labels into batches ready to be fed to a network). Feel free to get started on that!

**Comment by nicolas-chaulet** [comment]
Closing as it is done!
