### ISSUE TITLE
run "poetry run python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet" get "Sizes of tensors must match except in dimension 0." error in code batch.py

### ISSUE THREAD

**Issue by Yuwenger** [nicolas-chaulet/deeppointcloud-benchmarks#173]
hi alls :
   sorry to bother you~
I follow the process in readme, everything is ok, but when i run `poetry run python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_charlesssg dataset=shapenet
` error occurs .
`File "deeppointcloud-benchmarks/src/datasets/batch.py", line 48, in from_data_list
    batch[key] = torch.stack(batch[key])
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1576 and 2885 in dimension 1 at /pytorch/aten/src/TH/generic/THTensor.cpp:689`

**Comment by Yuwenger** [comment]
By the way， does this framwork only support fixed length data? how about arbitrary length point cloud?

**Comment by nicolas-chaulet** [comment]
Hi @Yuwenger ! Yes good spot we have just updated a couple of things in the code and missed older configs. It should be fixed soon, I'll tag you in the PR. The framework supports arbitrary length point cloud for some models (KPConv but not for others (Pointnet). It is a matter of rewriting some of the base modules to use the same data format as KPConv

**Comment by nicolas-chaulet** [comment]
@Yuwenger This should be fixed now. Thank you for your patience!

**Comment by Yuwenger** [comment]
> @Yuwenger This should be fixed now. Thank you for your patience!

great code , Thanks a lot ~

**Comment by Yuwenger** [comment]
@nicolas-chaulet 
thanks a lot ~
