### ISSUE TITLE
Differences with original RandLA-Net.

### ISSUE THREAD

**Issue by sgasperini** [nicolas-chaulet/deeppointcloud-benchmarks#209]
Hi, thank you for making this framework available!

I am interested in the **RandLA-Net** implementation.

I see you have two variants, namely Randlanet_Conv and Randlanet_Res.
I was wondering what are all the differences of the two compared to the unique original implementation, found here https://github.com/QingyongHu/RandLA-Net corresponding to the paper https://arxiv.org/abs/1911.11236 (where the network architecture is detailed in the appendix).

Could you please describe all the differences?

Thank you very much!

**Comment by nicolas-chaulet** [comment]
Hi @sgasperini ! We haven't worked on randla-net very much to be honest and when we implemented the source code was not available... So both models should be taken with a pinch of salt. To answer your question, the Conv is a single convolution block while the Res is a resnet block (two convolutions). 
We will be looking at bringing our version of randla-net up to speed in the near future and are always happy to receive contributions!

**Comment by sgasperini** [comment]
Hi @nicolas-chaulet!
Thank you for your quick reply and information.
The original source code should definitely help.
Thanks again and stay healthy!
