### ISSUE TITLE
Implement model saving and resume logic

### ISSUE THREAD

**Issue by nicolas-chaulet** [nicolas-chaulet/deeppointcloud-benchmarks#40]

**Comment by playertr** [comment]
Hello! What is the saving and resume logic that became implemented in this issue? 

I could not identify a Hydra argument to `train.py` that caused checkpoints to be resumed -- is training resumption only handled programmatically by importing `metrics.model_checkpoint`?

**Comment by playertr** [comment]
@nicolas-chaulet, did you implement a command line argument to resume training from a checkpoint? If not, perhaps I could make one and submit a PR.
